#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
quarto render prereg_causal_graph.qmd --to html
mv prereg_causal_graph.html ../results/
mv prereg_causal_graph_files ../results/
